page_actor_size: 6
load_followings: 5
load_know_users: 5
load_following_users_size: 4
page_movie_size: 6
index_movie_size: 3
random_movie_size: 5
load_more_comment_size: 2
load_more_reply_comment_size: 2
length_comment: 80
load_top_movies: 5
load_recent_movies: 3
load_reviews: 4
rate:
  rate_five: 5
  rate_four: 4
  rate_three: 3
  rate_two: 2
  rate_one: 1
search_objects: ["Movie", "Actor"]
length_name: 10
page_review_size: 3
